---
app:
  host: "localhost"
  port: 8080
  log_level: "ERROR"

sysdig:
  host: "https://us2.app.sysdig.com"
  # public_api_url: "https://<YOUR_CUSTOM_PUBLIC_API_URL>"

mcp:
  transport: stdio
  allowed_tools:
    - "threat-detection"
    - "cli-scanner" # You need the sysdig-cli-scanner binary installed in your server to use this tool
    - "vulnerability"
    - "inventory"
    - "sage"
