---
app:
  host: "localhost"
  port: 8080
  log_level: "ERROR"

sysdig:
  host: "https://secure.sysdig.com"

mcp:
  transport: stdio
  host: "localhost"
  port: 8080
  allowed_tools:
    - "events-feed"
    - "sysdig-cli-scanner" # Only available in stdio local transport mode
    - "vulnerability-management"
    - "inventory"
    - "sysdig-sage"
