---
app:
  host: "localhost"
  port: 8080
  log_level: "ERROR"

sysdig:
  host: "https://us2.app.sysdig.com"
  # public_api_url: "https://<YOUR_CUSTOM_PUBLIC_API_URL>"

mcp:
  transport: stdio
  host: "localhost"
  port: 8080
  allowed_tools:
    - "events-feed"
    - "sysdig-cli-scanner" # Only available in stdio local transport mode
    - "vulnerability-management"
    - "inventory"
    - "sysdig-sage"
