---
{{- if .Values.sysdig.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "sysdig-mcp.fullname" . }}-sysdig-secrets"
  labels:
    {{- include "sysdig-mcp.labels" . | nindent 4 }}
    release: {{ .Release.Name }}
type: Opaque
data:
  SYSDIG_SECURE_API_TOKEN: {{ .Values.sysdig.secrets.secureAPIToken | b64enc }}
{{- end }}
---
{{- if .Values.oauth.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "sysdig-mcp.fullname" . }}-oauth-secrets"
  labels:
    {{- include "sysdig-mcp.labels" . | nindent 4 }}
    release: {{ .Release.Name }}
type: Opaque
data:
  clientId: {{ .Values.oauth.secrets.clientId | b64enc }}
  clientSecret: {{ .Values.oauth.secrets.clientSecret | b64enc }}
{{- end }}
