name: Publish Docker image

on:
  push:
    branches:
      - main
    paths:
      - pyproject.toml

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read # required for actions/checkout
      packages: write # required for pushing to ghcr.io
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Extract version
        id: extract_version
        run: echo "VERSION=$(grep 'version =' pyproject.toml | sed -e 's/version = "\(.*\)"/\1/')-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/sysdiglabs/sysdig-mcp-server:latest
            ghcr.io/sysdiglabs/sysdig-mcp-server:v${{ env.VERSION }}
